---
windows_vm_storage_dir: "{{ libvirt_vm_storage_dir }}"
windows_vm_osinfo: win11
windows_vm_gateway: 10.10.20.1 # gateway que o Docker atribui pra pentest_network_subnet (10.10.20.0/24)
windows_vm_dns: "{{ dns_lan_ip }}"

windows_instances:
  - name: win11-a
    memory_mb: 8192
    vcpus: 4
    disk_gb: 80
    ip: 10.10.20.10
    vnc_port: 5910
  - name: win11-b
    memory_mb: 8192
    vcpus: 4
    disk_gb: 80
    ip: 10.10.20.11
    vnc_port: 5911
