[local]
localhost ansible_connection=local

[windows_vms]
win11-a ansible_host=10.10.20.10
win11-b ansible_host=10.10.20.11

[linux_targets]
linux-target ansible_host=10.10.20.20 ansible_user=gabriel ansible_ssh_private_key_file=~/.ssh/id_ed25519
