---
# Pacotes instalados via pacman (repositórios oficiais).
pacman_packages:
  - ansible
  - docker
  - docker-compose
  - dnsmasq

# Pacotes instalados via AUR (via paru, já presente no sistema).
aur_packages:
  - wazuh-agent
